### ISSUE TITLE
HMAC error when calling API functions

### ISSUE THREAD

**Issue by danepowell** [typhonius/acquia-php-sdk-v2#1]
I'm using `dev-master#8dfd3df`

I've initialized my Cloud API client like so:

```php
$cloud_api = Client::factory(array(
  'key' => $key,
  'secret' => $secret,
));
```

No problems with that. But when I try to call the API, such as `$cloud_api->applications();`, I get the following exception:
> Response is missing required X-Server-Authorization-HMAC-SHA256 header.

**Comment by danepowell** [comment]
Ah, apparently that's just what you get if authorization fails. It would be nice to capture that and translate it into a more user-friendly message.

**Comment by typhonius** [comment]
Good question. My (admittedly very basic) understanding of hmac auth is that there could be other reasons for not being authenticated such as machine time being too far out.

@itafroma @kevinhankens @charuag are top 3 committers to acquia/http-hmac-php - perhaps you could jump in and assist in this question.

**Comment by itafroma** [comment]
Hi guys! In addition to being one of the maintainers for acquia/http-hmac-php, I'm a software engineer working on the Cloud API v2.

You're receiving this error because the API is not currently not setting the `X-Server-Authorization-HMAC-SHA256` header for error responses. Because of this, acquia/http-hmac-php is acting correctly, at least according to the HTTP HMAC spec, in not "trusting" the actual response, instead simply reporting that the required header is missing.

I've filed a bug in our internal issue tracker to fix this issue.

**Comment by itafroma** [comment]
Hi guys! I'm one of the maintainers of acquia/http-hmac-php and a software engineer working on the Cloud API v2. Happy to help answer any questions.

According to HTTP HMAC spec:

> **If the server authenticates the request successfully,** it will add the following HTTP headers to the response (for all non-HEAD requests):
> ```
> X-Server-Authorization-HMAC-SHA256: <HMACServerAuthorization>
> ```

So this bug is in acquia/http-hmac-php: in the event it receives a response indicating the server could not authenticate the request, it should return the raw error instead of checking to see if `X-Server-Authorization-HMAC-SHA256` is set.

I've created https://github.com/acquia/http-hmac-php/issues/30 to track this issue in the library.

(I apologize for a (now deleted) inaccurate comment assigning the blame to the API.)

**Comment by typhonius** [comment]
@danepowell looks like this is now fixed upstream. When a new release is rolled for the library, I'll update this and we can close this issue.

**Comment by itafroma** [comment]
Hey again, acquia/http-hmac-php v3.2.1 has been released, fixing this issue.

**Comment by typhonius** [comment]
Thanks for your help @itafroma!
